### ISSUE TITLE
cdp.NewBrowser Reference

### ISSUE THREAD

**Issue by jamesnewsome** [PacktPublishing/Go-Web-Scraping-Quick-Start-Guide#1]
In your code in main.go https://github.com/PacktPublishing/Go-Web-Scraping-Quick-Start-Guide/tree/master/Chapter08/ch8ex2 

You reference cdp.NewBrowser however, Im not sure where that reference is coming from as your imports do not have NewBrowser function.

**Comment by Chiheb-Nexus** [comment]
Hi.
`cdp.NewBrowser` function is implemented in [Chrome Protocol package](https://github.com/4ydx/chrome-protocol) and precisely in this [part](https://github.com/4ydx/chrome-protocol/blob/d406265692c1f22dbba41632a38961cd7ad26da0/browser.go#L26-L109).

I'll close this thread because there isn't any reported issues with this code example.

Have a nice day.
